import React from "react";
import type { Slide } from "../types";
import { Server, Database, ShieldAlert, Cpu } from "lucide-react";
import { SlideTheme } from "../utils/themeUtils";
import { DecorativeElement } from "../components/DecorativeElement";
import SlideHeading from "../components/SlideHeading";

interface LayoutProps {
  slide: Slide;
  theme: SlideTheme;
}

export const ArchitectureLayout: React.FC<LayoutProps> = ({ slide, theme }) => {
  const zone = slide.zone_content || {};

  // Check if diagram_png is available (generated by matplotlib renderer)
  const diagramPng = (slide as any).diagram_png;

  const isTechnical = theme.decorativeShape === "glow";
  const cardBorder = isTechnical ? `1px solid ${theme.primary}` : `1px solid ${theme.cardBorder}`;
  const cardShadow = isTechnical ? theme.glowEffect : theme.cardShadow;

  // If diagram_png is available, display it directly (matches PPT export)
  if (diagramPng) {
    return (
      <div 
        className="layout-container architecture-layout"
        style={{
          backgroundColor: slide.background || theme.slideBackground,
          fontFamily: theme.bodyFont,
          width: '100%', height: '100%',
          position: 'relative',
          boxSizing: 'border-box',
          overflow: 'hidden',
        }}
      >
        <DecorativeElement theme={theme} position={{ top: '40px', right: '60px' }} />

        <div className="layout-header" style={{ marginBottom: '24px' }}>
          <SlideHeading
            title={slide.title}
            icon_emoji={slide.icon_emoji}
            theme={theme}
            slide={slide}
            zoneKey="title"
            style={{ marginBottom: 0 }}
          />
          <div style={{
            width: '60px', height: '4px',
            backgroundColor: theme.primary,
            borderRadius: '2px',
            marginTop: '12px',
            marginBottom: '16px'
          }} />
          {zone.subtitle && (
            <p 
              className="layout-subtitle"
              style={{
                color: theme.textMuted,
                fontWeight: '400',
                fontSize: '16px',
                margin: '8px 0 0 0',
              }}
            >
              {zone.subtitle}
            </p>
          )}
        </div>

        <div className="architecture-body" style={{ height: 'calc(100% - 140px)' }}>
          <div 
            className="diagram-canvas"
            style={{
              background: '#FFFFFF',
              border: cardBorder,
              boxShadow: cardShadow,
              borderRadius: '16px',
              position: 'relative',
              overflow: 'hidden',
              height: '100%',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
            }}
          >
            <img 
              src={diagramPng} 
              alt="Architecture Diagram" 
              style={{
                maxWidth: '100%',
                maxHeight: '100%',
                objectFit: 'contain',
              }}
            />
          </div>
        </div>
      </div>
    );
  }

  // Fallback to React rendering if no diagram_png
  const defaultNodes = [
    { id: "1", label: "API Gateway", x: 30, y: 100, type: "gateway" },
    { id: "2", label: "App Service", x: 180, y: 50, type: "service" },
    { id: "3", label: "Auth Worker", x: 180, y: 150, type: "service" },
    { id: "4", label: "Postgres DB", x: 340, y: 100, type: "database" },
  ];

  const defaultConnections = [
    { from: "1", to: "2" },
    { from: "1", to: "3" },
    { from: "2", to: "4" },
    { from: "3", to: "4" },
  ];

  let nodes = zone.nodes || null;
  let connections = zone.connections || null;

  if (!nodes && typeof zone.labels === "string") {
    const labelItems = zone.labels.split("\n").filter(Boolean);
    if (labelItems.length >= 2) {
      nodes = labelItems.map((lbl, idx) => {
        const types = ["gateway", "service", "service", "database"];
        const type = types[idx % types.length];
        const x = 30 + idx * 110;
        const y = 100 + (idx % 2 === 0 ? 0 : 40);
        return {
          id: String(idx + 1),
          label: lbl,
          x,
          y,
          type
        };
      });
      
      connections = [];
      for (let i = 0; i < nodes.length - 1; i++) {
        connections.push({ from: String(i + 1), to: String(i + 2) });
      }
    }
  }

  if (!nodes || !connections) {
    const listElement = slide.elements.find((el) => el.kind === "flow" || el.kind === "icon");
    if (listElement && listElement.items && listElement.items.length >= 3) {
      nodes = [
        { id: "1", label: listElement.items[0], x: 30, y: 100, type: "gateway" },
        { id: "2", label: listElement.items[1], x: 180, y: 100, type: "service" },
        { id: "3", label: listElement.items[2], x: 340, y: 100, type: "database" },
      ];
      connections = [
        { from: "1", to: "2" },
        { from: "2", to: "3" },
      ];
    } else {
      nodes = defaultNodes;
      connections = defaultConnections;
    }
  }

  // Draw SVG lines for connections
  // We need to map node ids to coordinate positions
  const nodeMap = new Map<string, any>(nodes.map((node: any) => [node.id, node]));

  return (
    <div 
      className="layout-container architecture-layout"
      style={{
        backgroundColor: slide.background || theme.slideBackground,
        fontFamily: theme.bodyFont,
        width: '100%', height: '100%',
        position: 'relative',
        boxSizing: 'border-box',
        overflow: 'hidden',
      }}
    >
      <DecorativeElement theme={theme} position={{ top: '40px', right: '60px' }} />

      <div className="layout-header" style={{ marginBottom: '24px' }}>
        <SlideHeading
          title={slide.title}
          icon_emoji={slide.icon_emoji}
          theme={theme}
          slide={slide}
          zoneKey="title"
          style={{ marginBottom: 0 }}
        />
        <div style={{
          width: '60px', height: '4px',
          backgroundColor: theme.primary,
          borderRadius: '2px',
          marginTop: '12px',
          marginBottom: '16px'
        }} />
        {zone.subtitle && (
          <p 
            className="layout-subtitle"
            style={{
              color: theme.textMuted,
              fontWeight: '400',
              fontSize: '16px',
              margin: '8px 0 0 0',
            }}
          >
            {zone.subtitle}
          </p>
        )}
      </div>

      <div className="architecture-body" style={{ display: 'grid', gridTemplateColumns: '1.3fr 0.7fr', gap: '24px', height: 'calc(100% - 140px)' }}>
        <div 
          className="diagram-canvas"
          style={{
            background: theme.cardBackground,
            border: cardBorder,
            boxShadow: cardShadow,
            borderRadius: '16px',
            position: 'relative',
            overflow: 'hidden',
            height: '100%',
          }}
        >
          {/* SVG Connector Overlay */}
          <svg className="diagram-svg-overlay" style={{ position: 'absolute', inset: 0, width: '100%', height: '100%', pointerEvents: 'none', zIndex: 1 }}>
            <defs>
              <marker
                id="arrow"
                viewBox="0 0 10 10"
                refX="6"
                refY="5"
                markerWidth="6"
                markerHeight="6"
                orient="auto-start-reverse"
              >
                <path d="M 0 2 L 10 5 L 0 8 z" fill={theme.primary} />
              </marker>
            </defs>
            {connections.map((conn: any, idx: number) => {
              const fromNode = nodeMap.get(conn.from);
              const toNode = nodeMap.get(conn.to);
              if (!fromNode || !toNode) return null;

              // Node dimensions (approximate for line centering: width 110px, height 38px)
              const startX = fromNode.x + 105;
              const startY = fromNode.y + 19;
              const endX = toNode.x - 5;
              const endY = toNode.y + 19;

              // Control points for bezier curves
              const cp1X = startX + 40;
              const cp1Y = startY;
              const cp2X = endX - 40;
              const cp2Y = endY;

              return (
                <path
                  key={idx}
                  d={`M ${startX} ${startY} C ${cp1X} ${cp1Y}, ${cp2X} ${cp2Y}, ${endX} ${endY}`}
                  fill="none"
                  stroke={theme.primary}
                  strokeWidth="2.5"
                  markerEnd="url(#arrow)"
                />
              );
            })}
          </svg>

          {/* Node Components */}
          {nodes.map((node: any) => {
            let nodeTypeColor = theme.primary;
            if (node.type === 'gateway') nodeTypeColor = theme.primary;
            else if (node.type === 'service') nodeTypeColor = theme.secondary;
            else if (node.type === 'database') nodeTypeColor = theme.accent || theme.primary;

            return (
              <div
                key={node.id}
                className={`diagram-node ${node.type}`}
                style={{ 
                  position: 'absolute',
                  left: `${node.x}px`, 
                  top: `${node.y}px`,
                  zIndex: 2,
                  background: theme.cardBackground,
                  border: `1.5px solid ${nodeTypeColor}`,
                  boxShadow: cardShadow,
                  color: theme.textHeading,
                  padding: "6px 12px",
                  fontSize: "12px",
                  fontWeight: 700,
                  borderRadius: "8px",
                  minWidth: "110px",
                  textAlign: "center",
                  height: "38px",
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                }}
              >
                <span style={{ overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>{node.label}</span>
              </div>
            );
          })}
        </div>

        <div 
          className="diagram-legend"
          style={{
            background: theme.cardBackground,
            border: cardBorder,
            boxShadow: cardShadow,
            borderRadius: '16px',
            padding: '24px',
            display: 'flex',
            flexDirection: 'column',
            justifyContent: 'space-between',
            height: '100%',
            boxSizing: 'border-box',
          }}
        >
          <div>
            <h2 
              className="legend-title"
              style={{
                color: theme.textHeading,
                fontWeight: '700',
                fontSize: '18px',
                margin: '0 0 16px 0',
              }}
            >
              System Legend
            </h2>
            <div className="legend-items" style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
              <div className="legend-item" style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
                <span className="legend-color" style={{ display: 'inline-block', width: '12px', height: '12px', borderRadius: '50%', background: theme.primary }} />
                <ShieldAlert size={14} style={{ color: theme.primary }} />
                <span style={{ fontSize: '13px', color: theme.textBody }}>Gateways (Ingress)</span>
              </div>
              <div className="legend-item" style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
                <span className="legend-color" style={{ display: 'inline-block', width: '12px', height: '12px', borderRadius: '50%', background: theme.secondary }} />
                <Cpu size={14} style={{ color: theme.secondary }} />
                <span style={{ fontSize: '13px', color: theme.textBody }}>Services (Logic)</span>
              </div>
              <div className="legend-item" style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
                <span className="legend-color" style={{ display: 'inline-block', width: '12px', height: '12px', borderRadius: '50%', background: theme.accent || theme.primary }} />
                <Database size={14} style={{ color: theme.accent || theme.primary }} />
                <span style={{ fontSize: '13px', color: theme.textBody }}>Databases (Store)</span>
              </div>
            </div>
          </div>
          <div style={{ fontSize: "11px", color: theme.textMuted, borderTop: `1px solid ${theme.cardBorder}`, paddingTop: "12px", marginTop: "12px" }}>
            This diagram demonstrates the secure communication path between decoupled stack components.
          </div>
        </div>
      </div>
    </div>
  );
};
